go: 
  version: 1.10.3
  cgo: true
repository:
  path: github.com/pytimer/gpu_exporter
build:
  binaries:
    - name: gpu_exporter
  flags: -tags 'netgo static_build'
  ldflags: |
    -X {{repoPath}}/main.Version={{.Version}}
crossbuild:
  platforms:
    - linux/amd64
