go: 
  version: 1.10.3
  cgo: true
repository:
  path: github.com/pytimer/gpu-exporter
build:
  binaries:
    - name: gpu-exporter
  static: false
  flags: -a -tags 'netgo static_build'
  ldflags: |
    -X {{repoPath}}/main.Version={{.Version}}
crossbuild:
  platforms:
    - linux/amd64
